language: node_js

node_js:
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - gulp test
  - gulp build-prod

deploy:
  provider: heroku
  strategy: api
  skip_cleanup: true
  all_branches: true
  api_key:
    secure: WPPWjujFXgNfPDznYIp4M4jXSwgb0eV/Jz1m2YGtgRnmI2IhnuG6leheuAEHdsq/PArfeIPDg3KJJoomWGDXLjt+Wj1I1srjmbMI4wvXh4UIvraqxo6W97TIq663/01Y/Vj+99ymd1cVhU6tkMmjJIsfDycjg1YE7WiEILCC2Yo=
  app: earlytwenties
  on:
    repo: Wildhoney/earlytwenties.co.uk
